---
- name: Install K3s Master Node
  shell: curl -sfL https://get.k3s.io | sh -
  environment:
    K3S_TOKEN: "{{ k3s_token }}"
    INSTALL_K3S_EXEC: "--write-kubeconfig-mode 644 --disable traefik"
  args:
    creates: /usr/local/bin/k3s
