[master]
ubuntu-desktop ansible_connection=local ansible_host=localhost

[worker]
wsl-laptop ansible_host=192.168.1.101 ansible_user=user ansible_become_password=REPLACE_ME

[all:vars]
k3s_token=supersecrettoken
k3s_url=https://192.168.1.100:6443
ansible_python_interpreter=/usr/bin/python3
