[master]
ubuntu-desktop ansible_host=10.8.22.147 ansible_user=z890

[worker]
wsl-laptop ansible_host=10.8.22.59 ansible_user=hhh

[all:vars]
k3s_token=supersecrettoken
k3s_url=https://10.8.22.147:6443
ansible_python_interpreter=/usr/bin/python3

