---
- name: Setup Prerequisites and Fix WSL GPU
  hosts: all
  become: true
  roles:
    - prerequisites

- name: Install K3s Master
  hosts: master
  become: true
  roles:
    - role: k3s
      vars:
        node_type: master

- name: Install K3s Worker
  hosts: worker
  become: true
  roles:
    - role: k3s
      vars:
        node_type: worker
